
### approve Vendor 2 by admin user #1
PUT localhost:8080/api/v1/vendor/2/approve/admin/1

### approve Vendor 3 by admin user #1
PUT localhost:8080/api/v1/vendor/3/approve/admin/1

### approve Vendor 4 by admin user #1
PUT localhost:8080/api/v1/vendor/4/approve/admin/1

### approve Vendor 5 by admin user #1
PUT localhost:8080/api/v1/vendor/5/approve/admin/1

### approve Vendor 6 by admin user #1
PUT localhost:8080/api/v1/vendor/6/approve/admin/1

### approve Vendor 7 by admin user #1
PUT localhost:8080/api/v1/vendor/7/approve/admin/1

### approve Vendor 8 by admin user #1
PUT localhost:8080/api/v1/vendor/8/approve/admin/1

### approve Vendor 9 by admin user #1
PUT localhost:8080/api/v1/vendor/9/approve/admin/1

### approve Vendor 10 by admin user #1
PUT localhost:8080/api/v1/vendor/10/approve/admin/1

### approve Vendor 11 by admin user #1
PUT localhost:8080/api/v1/vendor/11/approve/admin/1

### approve Vendor 12 by admin user #1
PUT localhost:8080/api/v1/vendor/12/approve/admin/1

### approve Vendor 13 by admin user #1
PUT localhost:8080/api/v1/vendor/13/approve/admin/1

### approve Vendor 14 by admin user #1
PUT localhost:8080/api/v1/vendor/14/approve/admin/1

### approve Vendor 15 by admin user #1
PUT localhost:8080/api/v1/vendor/15/approve/admin/1

### approve Vendor 1 by admin user #1
PUT localhost:8080/api/v1/vendor/1/approve/admin/1
