### approve Al-Mubarak Nursery by admin
PUT localhost:8080/api/v1/vendor/1/approve/admin/1


### Add Offer - Vendor 1 to Request 1 - Landscape Maintenance
POST http://localhost:8080/api/v1/offers/addOffer/1/1
Content-Type: application/json

{
  "price": 25000.00,
  "title": "Comprehensive Landscape Maintenance",
  "description": "Full-service package for Aramco campus, including weekly trimming, irrigation checks, and pest control."
}

### accept offer:
PUT localhost:8080/api/v1/offers/1/accept

### create contract:
POST localhost:8080/api/v1/offers/1/contract