package com.spring.boot.springbootcapstone3.DTO;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Setter
@Getter
@AllArgsConstructor
public class ContractDTOIn {
    // the ID is autogenerated from the serviceRequest id

    @NotNull(message = "totalPrice should not be empty")
    @Column(columnDefinition = "double not null")
    private double totalPrice;

    @NotNull(message = "startDate should not be empty")
    private LocalDateTime startDate;

    @NotNull(message = "endDate should not be empty")
    private LocalDateTime endDate;

    @NotEmpty(message = "careScope should not be empty")
    private String careScope; // JSON?

    // status should be assigned based on system flow?

    @NotEmpty(message = "contractLocationName should not be empty")
    private String contractLocationName;

    @NotEmpty(message = "contractLocationName should not be empty")
    private String contractLocationUrl;

    @NotEmpty(message = "contractItemsJson should not be empty")
    private String contractItemsJson;// JSON?

    // the invoice is added later after accepting the contract

    @NotNull(message = "serviceRequestId should not be empty")
    private Integer serviceRequestId;

    @NotNull(message = "organizationId should not be empty")
    private Integer organizationId;

    @NotNull(message = "vendorId should not be empty")
    private Integer vendorId;
}
