package com.spring.boot.springbootcapstone3.DTO;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@AllArgsConstructor
public class InvoiceDTOIn {
    // the ID is autogenerated from the contract id

    @NotEmpty(message = "toEmail should not be empty")
    private String toEmail;

    // calculated by the system
//    @Column(columnDefinition = "varchar(30) not null")
//    private String status;

    @NotEmpty(message = "paymentMethod should not be empty")
    private String paymentMethod;

    @NotEmpty(message = "providerReference should not be empty")
    private String providerReference;

    @NotNull(message = "contractId should not be empty")
    private Integer contractId;
}
